name: Push commit
on: push

jobs:
  push-code-and-test:
    name: Push code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Debug Repository Contents
        run: |
          ls -R

      - name: Run Tests
        run: |
          # Run your tests here
          python test_app.py

      - name: Run Check Snake Case Variables
        run: |
          # Run program here
          python vars_snake.py