name: Push commit
on: push

jobs:
  push-code-and-test:
    name: Push code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Changes
        run: |
          if [ -z "$(git ls-remote --heads origin main)" ]; then
            # Create the 'main' branch if it doesn't exist
            git checkout -b main
            git push origin main
          fi

          # Merge changes from 'temp_changes' into 'main'
          git merge temp_changes
          git push origin main

      - name: Debug Repository Contents
        run: |
          ls -R

      - name: Run Tests
        run: |
          # Run your tests here
          python test_app.py