name: Push Code and Run Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  push-code-and-test:
    name: Push code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Push code to repository
        run: |
          git config user.name "bclme"
          git config user.email "blas_lomibao@yahoo.com"
          git add .
          git commit -m "Pushing latest code"
          git push origin main  # Change 'main' to your branch name