name: Push Code and Run Tests

on:
  push:
    branches:
      - temp_changes
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  push-code-and-test:
    name: Push code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Changes
        run: |

            git branch --all -vv
  
            git merge temp_changes  # Merge changes from 'temp_changes' into 'main'
            git push origin main  # Push the merged changes to 'main'
 

      - name: Debug Repository Contents
        run: |
          ls -R

      - name: Run Tests
        run: |
          # Run your tests here
          python test_app.py