name: Push Code and Run Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  push-code-and-test:
    name: Push code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Changes
        run: |
          # Check if there are changes in the working directory
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "bclme"
            git config user.email "blas_lomibao@yahoo.com"
            git checkout -b temp_changes  # Create and switch to a new branch 'temp_changes'
            git add .
            git commit -m "Pushing latest code"
            git push origin temp_changes  # Push changes to 'temp_changes' branch
            git checkout main  # Switch back to the 'main' branch
            git merge temp_changes  # Merge changes from 'temp_changes' into 'main'
            git push origin main  # Push the merged changes to 'main'
          else
            echo "No changes to commit."
          fi

      - name: Debug Repository Contents
        run: |
          ls -R

      - name: Run Tests
        run: |
          # Run your tests here
          python test_app.py

